
package test.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TestWebServicePortType", targetNamespace = "http://test.com/testwebservice/1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TestWebServicePortType {


    /**
     * 
     * @param testWebServiceRequest
     * @return
     *     returns test.service.TestWebServiceResponseType
     */
    @WebMethod(action = "http://test.com/testwebservice/testOperation")
    @WebResult(name = "TestWebServiceResponse", targetNamespace = "http://test.com/testwebservice/1.0", partName = "TestWebServiceResponse")
    public TestWebServiceResponseType testOperation(
        @WebParam(name = "TestWebServiceRequest", targetNamespace = "http://test.com/testwebservice/1.0", partName = "TestWebServiceRequest")
        TestWebServiceRequestType testWebServiceRequest);

}
